-- Initial data population (!!!run ONCE only!!!)
INSERT OR IGNORE INTO SEARCH_INDEX_FTS5 (REGION, TABLE_TYPE, SEARCH_TEXT, SEASON_ID, REFERENCE_KEY)
SELECT 'EU', 'DEATHMATCH', NICKNAME, SEASON_ID, ID || '|' || SEASON_ID FROM EU_DEATHMATCH_RANKING
UNION ALL
SELECT 'EU', 'CLAN', TAG, SEASON_ID, TAG || '|' || SEASON_ID FROM EU_CLAN_RANKING
UNION ALL
SELECT 'AM', 'DEATHMATCH', NICKNAME, SEASON_ID, ID || '|' || SEASON_ID FROM AM_DEATHMATCH_RANKING
UNION ALL
SELECT 'AM', 'CLAN', TAG, SEASON_ID, TAG || '|' || SEASON_ID FROM AM_CLAN_RANKING
UNION ALL
SELECT 'ASIA', 'DEATHMATCH', NICKNAME, SEASON_ID, ID || '|' || SEASON_ID FROM ASIA_DEATHMATCH_RANKING
UNION ALL
SELECT 'ASIA', 'CLAN', TAG, SEASON_ID, TAG || '|' || SEASON_ID FROM ASIA_CLAN_RANKING;