PRAGMA journal_mode=WAL;
PRAGMA synchronous=NORMAL;
PRAGMA busy_timeout=5000;

-- EU SERVER
CREATE TABLE IF NOT EXISTS EU_DEATHMATCH_RANKING (
    ID INTEGER NOT NULL,
    SEASON_ID TEXT NOT NULL,
    NICKNAME TEXT NOT NULL,
    CLAN_TAG TEXT DEFAULT '',
    KILLS INTEGER DEFAULT 0,
    BOT_KILLS INTEGER DEFAULT 0,
    ELO REAL DEFAULT 1000,
    LOGS TEXT DEFAULT '',
    MATCH_PLAYED_COUNT INTEGER DEFAULT 0,
    PRIMARY KEY (ID, SEASON_ID)
);

CREATE INDEX IF NOT EXISTS INDEX_OF_EU_DEATHMATCH_KILLS ON EU_DEATHMATCH_RANKING(SEASON_ID, KILLS DESC);
CREATE INDEX IF NOT EXISTS INDEX_OF_EU_DEATHMATCH_BOT_KILLS ON EU_DEATHMATCH_RANKING(SEASON_ID, BOT_KILLS DESC);
CREATE INDEX IF NOT EXISTS INDEX_OF_EU_DEATHMATCH_ELO ON EU_DEATHMATCH_RANKING(SEASON_ID, ELO DESC);

CREATE TABLE IF NOT EXISTS EU_CLAN_RANKING (
    TAG TEXT NOT NULL,
    SEASON_ID TEXT NOT NULL,
    NAME TEXT NOT NULL,
    ELO_ADDEND REAL DEFAULT 0,
    ELO_SUBTRAHEND REAL DEFAULT 0,
    ELO REAL DEFAULT 1000,
    LOGS TEXT DEFAULT '',
    PRIMARY KEY (TAG, SEASON_ID)
);

CREATE INDEX IF NOT EXISTS INDEX_OF_EU_CLAN_ELO ON EU_CLAN_RANKING(SEASON_ID, ELO DESC);

-- AM SERVER
CREATE TABLE IF NOT EXISTS AM_DEATHMATCH_RANKING (
    ID INTEGER NOT NULL,
    SEASON_ID TEXT NOT NULL,
    NICKNAME TEXT NOT NULL,
    CLAN_TAG TEXT DEFAULT '',
    KILLS INTEGER DEFAULT 0,
    BOT_KILLS INTEGER DEFAULT 0,
    ELO REAL DEFAULT 1000,
    LOGS TEXT DEFAULT '',
    MATCH_PLAYED_COUNT INTEGER DEFAULT 0,
    PRIMARY KEY (ID, SEASON_ID)
);

CREATE INDEX IF NOT EXISTS INDEX_OF_AM_DEATHMATCH_KILLS ON AM_DEATHMATCH_RANKING(SEASON_ID, KILLS DESC);
CREATE INDEX IF NOT EXISTS INDEX_OF_AM_DEATHMATCH_BOT_KILLS ON AM_DEATHMATCH_RANKING(SEASON_ID, BOT_KILLS DESC);
CREATE INDEX IF NOT EXISTS INDEX_OF_AM_DEATHMATCH_ELO ON AM_DEATHMATCH_RANKING(SEASON_ID, ELO DESC);

CREATE TABLE IF NOT EXISTS AM_CLAN_RANKING (
    TAG TEXT NOT NULL,
    SEASON_ID TEXT NOT NULL,
    NAME TEXT NOT NULL,
    ELO_ADDEND REAL DEFAULT 0,
    ELO_SUBTRAHEND REAL DEFAULT 0,
    ELO REAL DEFAULT 1000,
    LOGS TEXT DEFAULT '',
    PRIMARY KEY (TAG, SEASON_ID)
);

CREATE INDEX IF NOT EXISTS INDEX_OF_AM_CLAN_ELO ON AM_CLAN_RANKING(SEASON_ID, ELO DESC);

-- ASIA SERVER
CREATE TABLE IF NOT EXISTS ASIA_DEATHMATCH_RANKING (
    ID INTEGER NOT NULL,
    SEASON_ID TEXT NOT NULL,
    NICKNAME TEXT NOT NULL,
    CLAN_TAG TEXT DEFAULT '',
    KILLS INTEGER DEFAULT 0,
    BOT_KILLS INTEGER DEFAULT 0,
    ELO REAL DEFAULT 1000,
    LOGS TEXT DEFAULT '',
    MATCH_PLAYED_COUNT INTEGER DEFAULT 0,
    PRIMARY KEY (ID, SEASON_ID)
);

CREATE INDEX IF NOT EXISTS INDEX_OF_ASIA_DEATHMATCH_KILLS ON ASIA_DEATHMATCH_RANKING(SEASON_ID, KILLS DESC);
CREATE INDEX IF NOT EXISTS INDEX_OF_ASIA_DEATHMATCH_BOT_KILLS ON ASIA_DEATHMATCH_RANKING(SEASON_ID, BOT_KILLS DESC);
CREATE INDEX IF NOT EXISTS INDEX_OF_ASIA_DEATHMATCH_ELO ON ASIA_DEATHMATCH_RANKING(SEASON_ID, ELO DESC);

CREATE TABLE IF NOT EXISTS ASIA_CLAN_RANKING (
    TAG TEXT NOT NULL,
    SEASON_ID TEXT NOT NULL,
    NAME TEXT NOT NULL,
    ELO_ADDEND REAL DEFAULT 0,
    ELO_SUBTRAHEND REAL DEFAULT 0,
    ELO REAL DEFAULT 1000,
    LOGS TEXT DEFAULT '',
    PRIMARY KEY (TAG, SEASON_ID)
);

CREATE INDEX IF NOT EXISTS INDEX_OF_ASIA_CLAN_ELO ON ASIA_CLAN_RANKING(SEASON_ID, ELO DESC);

-- UNIFIED SEARCH INDEX
CREATE VIRTUAL TABLE IF NOT EXISTS SEARCH_INDEX_FTS5 USING fts5(
    REGION,          -- 'EU', 'AM', 'ASIA'
    TABLE_TYPE,      -- 'DEATHMATCH', 'CLAN'
    SEARCH_TEXT,     -- NICKNAME or TAG
    SEASON_ID,
    REFERENCE_KEY,    -- For Deathmatch: 'ID|SEASON_ID', For Clan: 'TAG|SEASON_ID'
    tokenize = "trigram"
);

-- Triggers for EU Deathmatch
CREATE TRIGGER IF NOT EXISTS EU_DEATHMATCH_RANKING_INSERT_TRIGGER AFTER INSERT ON EU_DEATHMATCH_RANKING
BEGIN
    INSERT INTO SEARCH_INDEX_FTS5 (REGION, TABLE_TYPE, SEARCH_TEXT, SEASON_ID, REFERENCE_KEY)
    VALUES ('EU', 'DEATHMATCH', new.NICKNAME, new.SEASON_ID, new.ID || '|' || new.SEASON_ID);
END;

CREATE TRIGGER IF NOT EXISTS EU_DEATHMATCH_RANKING_UPDATE_TRIGGER AFTER UPDATE ON EU_DEATHMATCH_RANKING
BEGIN
    DELETE FROM SEARCH_INDEX_FTS5 WHERE REFERENCE_KEY = old.ID || '|' || old.SEASON_ID AND REGION = 'EU' AND TABLE_TYPE = 'DEATHMATCH';
    INSERT INTO SEARCH_INDEX_FTS5 (REGION, TABLE_TYPE, SEARCH_TEXT, SEASON_ID, REFERENCE_KEY)
    VALUES ('EU', 'DEATHMATCH', new.NICKNAME, new.SEASON_ID, new.ID || '|' || new.SEASON_ID);
END;

CREATE TRIGGER IF NOT EXISTS EU_DEATHMATCH_RANKING_DELETE_TRIGGER AFTER DELETE ON EU_DEATHMATCH_RANKING
BEGIN
    DELETE FROM SEARCH_INDEX_FTS5 WHERE REFERENCE_KEY = old.ID || '|' || old.SEASON_ID AND REGION = 'EU' AND TABLE_TYPE = 'DEATHMATCH';
END;

-- Triggers for EU Clan
CREATE TRIGGER IF NOT EXISTS EU_CLAN_RANKING_INSERT_TRIGGER AFTER INSERT ON EU_CLAN_RANKING
BEGIN
    INSERT INTO SEARCH_INDEX_FTS5 (REGION, TABLE_TYPE, SEARCH_TEXT, SEASON_ID, REFERENCE_KEY)
    VALUES ('EU', 'CLAN', new.TAG, new.SEASON_ID, new.TAG || '|' || new.SEASON_ID);
END;

CREATE TRIGGER IF NOT EXISTS EU_CLAN_RANKING_UPDATE_TRIGGER AFTER UPDATE ON EU_CLAN_RANKING
BEGIN
    DELETE FROM SEARCH_INDEX_FTS5 WHERE REFERENCE_KEY = old.TAG || '|' || old.SEASON_ID AND REGION = 'EU' AND TABLE_TYPE = 'CLAN';
    INSERT INTO SEARCH_INDEX_FTS5 (REGION, TABLE_TYPE, SEARCH_TEXT, SEASON_ID, REFERENCE_KEY)
    VALUES ('EU', 'CLAN', new.TAG, new.SEASON_ID, new.TAG || '|' || new.SEASON_ID);
END;

CREATE TRIGGER IF NOT EXISTS EU_CLAN_RANKING_DELETE_TRIGGER AFTER DELETE ON EU_CLAN_RANKING
BEGIN
    DELETE FROM SEARCH_INDEX_FTS5 WHERE REFERENCE_KEY = old.TAG || '|' || old.SEASON_ID AND REGION = 'EU' AND TABLE_TYPE = 'CLAN';
END;

-- Triggers for AM Deathmatch
CREATE TRIGGER IF NOT EXISTS AM_DEATHMATCH_RANKING_INSERT_TRIGGER AFTER INSERT ON AM_DEATHMATCH_RANKING
BEGIN
    INSERT INTO SEARCH_INDEX_FTS5 (REGION, TABLE_TYPE, SEARCH_TEXT, SEASON_ID, REFERENCE_KEY)
    VALUES ('AM', 'DEATHMATCH', new.NICKNAME, new.SEASON_ID, new.ID || '|' || new.SEASON_ID);
END;

CREATE TRIGGER IF NOT EXISTS AM_DEATHMATCH_RANKING_UPDATE_TRIGGER AFTER UPDATE ON AM_DEATHMATCH_RANKING
BEGIN
    DELETE FROM SEARCH_INDEX_FTS5 WHERE REFERENCE_KEY = old.ID || '|' || old.SEASON_ID AND REGION = 'AM' AND TABLE_TYPE = 'DEATHMATCH';
    INSERT INTO SEARCH_INDEX_FTS5 (REGION, TABLE_TYPE, SEARCH_TEXT, SEASON_ID, REFERENCE_KEY)
    VALUES ('AM', 'DEATHMATCH', new.NICKNAME, new.SEASON_ID, new.ID || '|' || new.SEASON_ID);
END;

CREATE TRIGGER IF NOT EXISTS AM_DEATHMATCH_RANKING_DELETE_TRIGGER AFTER DELETE ON AM_DEATHMATCH_RANKING
BEGIN
    DELETE FROM SEARCH_INDEX_FTS5 WHERE REFERENCE_KEY = old.ID || '|' || old.SEASON_ID AND REGION = 'AM' AND TABLE_TYPE = 'DEATHMATCH';
END;

-- Triggers for AM Clan
CREATE TRIGGER IF NOT EXISTS AM_CLAN_RANKING_INSERT_TRIGGER AFTER INSERT ON AM_CLAN_RANKING
BEGIN
    INSERT INTO SEARCH_INDEX_FTS5 (REGION, TABLE_TYPE, SEARCH_TEXT, SEASON_ID, REFERENCE_KEY)
    VALUES ('AM', 'CLAN', new.TAG, new.SEASON_ID, new.TAG || '|' || new.SEASON_ID);
END;

CREATE TRIGGER IF NOT EXISTS AM_CLAN_RANKING_UPDATE_TRIGGER AFTER UPDATE ON AM_CLAN_RANKING
BEGIN
    DELETE FROM SEARCH_INDEX_FTS5 WHERE REFERENCE_KEY = old.TAG || '|' || old.SEASON_ID AND REGION = 'AM' AND TABLE_TYPE = 'CLAN';
    INSERT INTO SEARCH_INDEX_FTS5 (REGION, TABLE_TYPE, SEARCH_TEXT, SEASON_ID, REFERENCE_KEY)
    VALUES ('AM', 'CLAN', new.TAG, new.SEASON_ID, new.TAG || '|' || new.SEASON_ID);
END;

CREATE TRIGGER IF NOT EXISTS AM_CLAN_RANKING_DELETE_TRIGGER AFTER DELETE ON AM_CLAN_RANKING
BEGIN
    DELETE FROM SEARCH_INDEX_FTS5 WHERE REFERENCE_KEY = old.TAG || '|' || old.SEASON_ID AND REGION = 'AM' AND TABLE_TYPE = 'CLAN';
END;

-- Triggers for ASIA Deathmatch
CREATE TRIGGER IF NOT EXISTS ASIA_DEATHMATCH_RANKING_INSERT_TRIGGER AFTER INSERT ON ASIA_DEATHMATCH_RANKING
BEGIN
    INSERT INTO SEARCH_INDEX_FTS5 (REGION, TABLE_TYPE, SEARCH_TEXT, SEASON_ID, REFERENCE_KEY)
    VALUES ('ASIA', 'DEATHMATCH', new.NICKNAME, new.SEASON_ID, new.ID || '|' || new.SEASON_ID);
END;

CREATE TRIGGER IF NOT EXISTS ASIA_DEATHMATCH_RANKING_UPDATE_TRIGGER AFTER UPDATE ON ASIA_DEATHMATCH_RANKING
BEGIN
    DELETE FROM SEARCH_INDEX_FTS5 WHERE REFERENCE_KEY = old.ID || '|' || old.SEASON_ID AND REGION = 'ASIA' AND TABLE_TYPE = 'DEATHMATCH';
    INSERT INTO SEARCH_INDEX_FTS5 (REGION, TABLE_TYPE, SEARCH_TEXT, SEASON_ID, REFERENCE_KEY)
    VALUES ('ASIA', 'DEATHMATCH', new.NICKNAME, new.SEASON_ID, new.ID || '|' || new.SEASON_ID);
END;

CREATE TRIGGER IF NOT EXISTS ASIA_DEATHMATCH_RANKING_DELETE_TRIGGER AFTER DELETE ON ASIA_DEATHMATCH_RANKING
BEGIN
    DELETE FROM SEARCH_INDEX_FTS5 WHERE REFERENCE_KEY = old.ID || '|' || old.SEASON_ID AND REGION = 'ASIA' AND TABLE_TYPE = 'DEATHMATCH';
END;

-- Triggers for ASIA Clan
CREATE TRIGGER IF NOT EXISTS ASIA_CLAN_RANKING_INSERT_TRIGGER AFTER INSERT ON ASIA_CLAN_RANKING
BEGIN
    INSERT INTO SEARCH_INDEX_FTS5 (REGION, TABLE_TYPE, SEARCH_TEXT, SEASON_ID, REFERENCE_KEY)
    VALUES ('ASIA', 'CLAN', new.TAG, new.SEASON_ID, new.TAG || '|' || new.SEASON_ID);
END;

CREATE TRIGGER IF NOT EXISTS ASIA_CLAN_RANKING_UPDATE_TRIGGER AFTER UPDATE ON ASIA_CLAN_RANKING
BEGIN
    DELETE FROM SEARCH_INDEX_FTS5 WHERE REFERENCE_KEY = old.TAG || '|' || old.SEASON_ID AND REGION = 'ASIA' AND TABLE_TYPE = 'CLAN';
    INSERT INTO SEARCH_INDEX_FTS5 (REGION, TABLE_TYPE, SEARCH_TEXT, SEASON_ID, REFERENCE_KEY)
    VALUES ('ASIA', 'CLAN', new.TAG, new.SEASON_ID, new.TAG || '|' || new.SEASON_ID);
END;

CREATE TRIGGER IF NOT EXISTS ASIA_CLAN_RANKING_DELETE_TRIGGER AFTER DELETE ON ASIA_CLAN_RANKING
BEGIN
    DELETE FROM SEARCH_INDEX_FTS5 WHERE REFERENCE_KEY = old.TAG || '|' || old.SEASON_ID AND REGION = 'ASIA' AND TABLE_TYPE = 'CLAN';
END;