-- sqlite

CREATE TABLE IF NOT EXISTS EU_PEAKS (
    TIMESTAMP INTEGER PRIMARY KEY,
    PLAYER_COUNT INTEGER NOT NULL
) WITHOUT ROWID;

CREATE INDEX IF NOT EXISTS peaks_index ON EU_PEAKS(TIMESTAMP, PLAYER_COUNT);

CREATE TABLE IF NOT EXISTS AM_PEAKS (
    TIMESTAMP INTEGER PRIMARY KEY,
    PLAYER_COUNT INTEGER NOT NULL
) WITHOUT ROWID;

CREATE INDEX IF NOT EXISTS peaks_index ON AM_PEAKS(TIMESTAMP, PLAYER_COUNT);

CREATE TABLE IF NOT EXISTS ASIA_PEAKS (
    TIMESTAMP INTEGER PRIMARY KEY,
    PLAYER_COUNT INTEGER NOT NULL
) WITHOUT ROWID;

CREATE INDEX IF NOT EXISTS peaks_index ON ASIA_PEAKS(TIMESTAMP, PLAYER_COUNT);