CREATE TABLE IF NOT EXISTS REPLAY_METADATA (
    ID TEXT PRIMARY KEY, -- [server_index]-[mode_index]-[game-id]-[timestamp]
    SERVER_INDEX INTEGER NOT NULL,
    MODE_INDEX INTEGER NOT NULL,
    TIMESTAMP INTEGER NOT NULL,
    SIZE INTEGER NOT NULL,
    TITLE TEXT NOT NULL,
    INFO TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS INDEX_OF_METADATA_FILTER ON REPLAY_METADATA(SERVER_INDEX, MODE_INDEX, TIMESTAMP DESC);

CREATE TABLE IF NOT EXISTS REPLAY_JSONS (
    ID TEXT PRIMARY KEY,
    JSON TEXT NOT NULL
);