CREATE TABLE IF NOT EXISTS DMS_RADIO_RECEIVERS (
    DISCORD_USER_ID INTEGER PRIMARY KEY
) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS FAVORITE_PLAYERS (
    DISCORD_USER_ID INTEGER NOT NULL,
    PLAYER_ID INTEGER NOT NULL,
    NICKNAME TEXT NOT NULL,
    PRIMARY KEY (DISCORD_USER_ID, PLAYER_ID)
) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS FAVORITE_CLANS (
    DISCORD_USER_ID INTEGER NOT NULL,
    CLAN_TAG INTEGER NOT NULL,
    PRIMARY KEY (DISCORD_USER_ID, CLAN_TAG)
) WITHOUT ROWID;